"""
PDF Generator — GeeksforGeeks PHP Learning Module
Generates a professional academic handout PDF from scraped data.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from datetime import datetime
import os

# ── Color palette ──────────────────────────────────────────────
GFG_GREEN    = colors.HexColor("#2F8D46")
GFG_DARK     = colors.HexColor("#1A5C2A")
GFG_LIGHT    = colors.HexColor("#E8F5E9")
GFG_ACCENT   = colors.HexColor("#F4A71D")
DARK_GRAY    = colors.HexColor("#2D2D2D")
MID_GRAY     = colors.HexColor("#555555")
LIGHT_GRAY   = colors.HexColor("#F5F5F5")
CODE_BG      = colors.HexColor("#1E1E1E")
CODE_FG      = colors.HexColor("#D4D4D4")
BORDER_COLOR = colors.HexColor("#C8E6C9")


# ── Page header/footer callback ────────────────────────────────
class PageTemplate:
    def __init__(self, student_name: str, total_articles: int):
        self.student_name = student_name
        self.total_articles = total_articles

    def __call__(self, canvas_obj, doc):
        canvas_obj.saveState()
        w, h = A4

        # ── Top header bar ──
        canvas_obj.setFillColor(GFG_GREEN)
        canvas_obj.rect(0, h - 28*mm, w, 28*mm, fill=1, stroke=0)

        # Header text
        canvas_obj.setFillColor(colors.white)
        canvas_obj.setFont("Helvetica-Bold", 13)
        canvas_obj.drawString(15*mm, h - 13*mm, "GeeksforGeeks")
        canvas_obj.setFont("Helvetica", 9)
        canvas_obj.drawString(15*mm, h - 20*mm, "PHP Programming — Learning Module")

        # Right side: date + subject
        canvas_obj.setFont("Helvetica", 8)
        date_str = datetime.now().strftime("%B %d, %Y")
        canvas_obj.drawRightString(w - 15*mm, h - 13*mm, f"Generated: {date_str}")
        canvas_obj.drawRightString(w - 15*mm, h - 20*mm, "Subject Category: PHP / Web Development")

        # ── Footer bar ──
        canvas_obj.setFillColor(GFG_DARK)
        canvas_obj.rect(0, 0, w, 14*mm, fill=1, stroke=0)

        canvas_obj.setFillColor(colors.white)
        canvas_obj.setFont("Helvetica", 7.5)
        canvas_obj.drawString(15*mm, 5*mm,
            f"Generated by {self.student_name}  |  Source: geeksforgeeks.org  |  {self.total_articles} Topics Covered")
        canvas_obj.setFont("Helvetica-Bold", 8)
        canvas_obj.drawRightString(w - 15*mm, 5*mm, f"Page {doc.page}")

        canvas_obj.restoreState()


def build_styles() -> dict:
    base = getSampleStyleSheet()

    styles = {
        "cover_title": ParagraphStyle(
            "cover_title",
            fontSize=28, fontName="Helvetica-Bold",
            textColor=colors.white, alignment=TA_CENTER,
            spaceAfter=6,
        ),
        "cover_sub": ParagraphStyle(
            "cover_sub",
            fontSize=13, fontName="Helvetica",
            textColor=colors.HexColor("#C8E6C9"), alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "cover_meta": ParagraphStyle(
            "cover_meta",
            fontSize=10, fontName="Helvetica",
            textColor=colors.HexColor("#A5D6A7"), alignment=TA_CENTER,
        ),
        "toc_title": ParagraphStyle(
            "toc_title",
            fontSize=16, fontName="Helvetica-Bold",
            textColor=GFG_DARK, spaceAfter=12, spaceBefore=6,
        ),
        "toc_entry": ParagraphStyle(
            "toc_entry",
            fontSize=10, fontName="Helvetica",
            textColor=DARK_GRAY, spaceAfter=4, leftIndent=10,
        ),
        "article_num": ParagraphStyle(
            "article_num",
            fontSize=9, fontName="Helvetica-Bold",
            textColor=colors.white, alignment=TA_CENTER,
        ),
        "article_title": ParagraphStyle(
            "article_title",
            fontSize=15, fontName="Helvetica-Bold",
            textColor=GFG_DARK, spaceBefore=4, spaceAfter=6,
        ),
        "section_head": ParagraphStyle(
            "section_head",
            fontSize=10, fontName="Helvetica-Bold",
            textColor=GFG_GREEN, spaceAfter=4, spaceBefore=8,
        ),
        "body": ParagraphStyle(
            "body",
            fontSize=9.5, fontName="Helvetica",
            textColor=DARK_GRAY, alignment=TA_JUSTIFY,
            spaceAfter=6, leading=14,
        ),
        "code": ParagraphStyle(
            "code",
            fontSize=8, fontName="Courier",
            textColor=CODE_FG, backColor=CODE_BG,
            leftIndent=8, rightIndent=8,
            spaceAfter=6, spaceBefore=4,
            leading=12, borderPadding=(6, 8, 6, 8),
        ),
        "na": ParagraphStyle(
            "na",
            fontSize=9, fontName="Helvetica-Oblique",
            textColor=colors.HexColor("#9E9E9E"), spaceAfter=4,
        ),
        "url": ParagraphStyle(
            "url",
            fontSize=8, fontName="Helvetica",
            textColor=colors.HexColor("#1565C0"), spaceAfter=3,
        ),
        "difficulty_easy": ParagraphStyle(
            "diff_easy",
            fontSize=9, fontName="Helvetica-Bold",
            textColor=colors.HexColor("#2E7D32"),
        ),
        "difficulty_medium": ParagraphStyle(
            "diff_med",
            fontSize=9, fontName="Helvetica-Bold",
            textColor=colors.HexColor("#E65100"),
        ),
        "difficulty_hard": ParagraphStyle(
            "diff_hard",
            fontSize=9, fontName="Helvetica-Bold",
            textColor=colors.HexColor("#B71C1C"),
        ),
        "difficulty_na": ParagraphStyle(
            "diff_na",
            fontSize=9, fontName="Helvetica",
            textColor=MID_GRAY,
        ),
    }
    return styles


def difficulty_style(difficulty: str, styles: dict) -> ParagraphStyle:
    d = difficulty.lower()
    if "easy" in d or "basic" in d:
        return styles["difficulty_easy"]
    elif "medium" in d:
        return styles["difficulty_medium"]
    elif "hard" in d or "expert" in d:
        return styles["difficulty_hard"]
    return styles["difficulty_na"]


def section_label(text: str, styles: dict) -> list:
    """Returns a colored label row for a section."""
    return [
        HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR, spaceAfter=2),
        Paragraph(f"▸  {text}", styles["section_head"]),
    ]


def build_cover_page(story: list, styles: dict, student_name: str,
                     total: int, date_str: str):
    """Build a full cover page."""
    w, h = A4

    # Big green cover background via a table
    cover_data = [[
        Paragraph("GeeksforGeeks", styles["cover_title"]),
    ]]
    cover_table = Table(cover_data, colWidths=[w - 4*cm])
    cover_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), GFG_GREEN),
        ("TOPPADDING", (0, 0), (-1, -1), 60),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 20),
        ("LEFTPADDING", (0, 0), (-1, -1), 20),
        ("RIGHTPADDING", (0, 0), (-1, -1), 20),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [GFG_GREEN]),
    ]))
    story.append(cover_table)

    # Sub info block
    info_data = [
        [Paragraph("PHP Programming", styles["cover_sub"])],
        [Paragraph("Learning Module &amp; Study Guide", styles["cover_sub"])],
        [Spacer(1, 8)],
        [Paragraph(f"Total Topics Covered: <b>{total}</b>", styles["cover_meta"])],
        [Paragraph(f"Date of Generation: <b>{date_str}</b>", styles["cover_meta"])],
        [Paragraph(f"Generated by: <b>{student_name}</b>", styles["cover_meta"])],
        [Paragraph("Source: geeksforgeeks.org", styles["cover_meta"])],
    ]
    info_table = Table(info_data, colWidths=[w - 4*cm])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), GFG_DARK),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 20),
        ("RIGHTPADDING", (0, 0), (-1, -1), 20),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(info_table)
    story.append(PageBreak())


def build_toc(story: list, styles: dict, articles: list):
    """Build a Table of Contents page."""
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph("Table of Contents", styles["toc_title"]))
    story.append(HRFlowable(width="100%", thickness=1.5, color=GFG_GREEN, spaceAfter=10))

    for i, art in enumerate(articles, 1):
        title = art.get("title", "Untitled")
        diff = art.get("difficulty", "Not Available")
        diff_color = "#2E7D32" if "easy" in diff.lower() or "basic" in diff.lower() \
            else "#E65100" if "medium" in diff.lower() \
            else "#B71C1C" if "hard" in diff.lower() \
            else "#757575"
        entry = (
            f'<font color="#2D2D2D"><b>{i:02d}.</b></font>  '
            f'{title}  '
            f'<font color="{diff_color}"><i>[{diff}]</i></font>'
        )
        story.append(Paragraph(entry, styles["toc_entry"]))

    story.append(PageBreak())


def build_article_section(story: list, styles: dict, article: dict, index: int):
    """Build one article's content block."""
    w, _ = A4
    col_w = w - 4*cm

    elements = []

    # ── Article header bar ──
    num_data = [[Paragraph(f"{index:02d}", styles["article_num"])]]
    num_table = Table(num_data, colWidths=[1.2*cm], rowHeights=[1.2*cm])
    num_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), GFG_GREEN),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))

    title_text = article.get("title", "Untitled Article")
    title_para = Paragraph(title_text, styles["article_title"])

    header_data = [[num_table, title_para]]
    header_table = Table(header_data, colWidths=[1.5*cm, col_w - 1.5*cm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(header_table)

    # Difficulty badge
    diff = article.get("difficulty", "Not Available")
    diff_style = difficulty_style(diff, styles)
    elements.append(Paragraph(f"Difficulty Level:  {diff}", diff_style))
    elements.append(Spacer(1, 4))

    # ── Key Technical Concepts ──
    elements += section_label("Key Technical Concepts", styles)
    concepts = article.get("key_concepts", "Not Available")
    style = styles["na"] if concepts == "Not Available" else styles["body"]
    elements.append(Paragraph(concepts, style))

    # ── Code Snippet ──
    elements += section_label("Code Snippet / Implementation", styles)
    code = article.get("code_snippet", "Not Available")
    if code == "Not Available":
        elements.append(Paragraph("Not Available", styles["na"]))
    else:
        # Escape XML chars for ReportLab
        safe_code = code.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        code_data = [[Paragraph(safe_code, styles["code"])]]
        code_table = Table(code_data, colWidths=[col_w])
        code_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), CODE_BG),
            ("ROUNDEDCORNERS", [4, 4, 4, 4]),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        elements.append(code_table)

    # ── Complexity Analysis ──
    elements += section_label("Complexity Analysis", styles)
    complexity = article.get("complexity", "Not Available")
    style = styles["na"] if complexity == "Not Available" else styles["body"]
    elements.append(Paragraph(complexity, style))

    # ── References / Related Links ──
    elements += section_label("References / Related Links", styles)
    links = article.get("related_links", "Not Available")
    if links == "Not Available":
        elements.append(Paragraph("Not Available", styles["na"]))
    else:
        for link in links.split("; "):
            link = link.strip()
            if link:
                elements.append(Paragraph(f"• {link}", styles["url"]))

    # ── Source URL ──
    url = article.get("url", "")
    if url:
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(f"Source: {url}", styles["url"]))

    # Bottom separator
    elements.append(Spacer(1, 6))
    elements.append(HRFlowable(width="100%", thickness=0.8, color=BORDER_COLOR))
    elements.append(Spacer(1, 8))

    story.append(KeepTogether(elements[:6]))  # Keep header together
    story.extend(elements[6:])


def generate_pdf(articles: list[dict], output_path: str, student_name: str = "Student") -> str:
    """
    Generate a professional academic PDF learning module.
    Returns the output file path.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    date_str = datetime.now().strftime("%B %d, %Y")
    page_cb = PageTemplate(student_name, len(articles))

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=2*cm,
        rightMargin=2*cm,
        topMargin=3.5*cm,
        bottomMargin=2.2*cm,
        title="GFG PHP Learning Module",
        author=student_name,
        subject="PHP Programming",
    )

    styles = build_styles()
    story = []

    # Cover page (no header/footer)
    build_cover_page(story, styles, student_name, len(articles), date_str)

    # Table of Contents
    build_toc(story, styles, articles)

    # Article sections
    for i, article in enumerate(articles, 1):
        build_article_section(story, styles, article, i)
        if i < len(articles):
            story.append(PageBreak())

    doc.build(story, onFirstPage=page_cb, onLaterPages=page_cb)
    return output_path


if __name__ == "__main__":
    import json
    with open("articles.json", "r", encoding="utf-8") as f:
        articles = json.load(f)
    out = generate_pdf(articles, "php_learning_module.pdf", "Test Student")
    print(f"PDF saved to: {out}")